# Generated by Django 3.0.8 on 2020-07-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200721_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auctionier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
