# Generated by Django 3.0.8 on 2020-07-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200726_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishes',
            new_name='checked',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='listing',
            new_name='listing_id',
        ),
    ]
