# Generated by Django 3.0.8 on 2020-07-27 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200726_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='admirer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admirer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='bid_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='category',
            field=models.CharField(default='cloth', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(default='image', upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='title',
            field=models.CharField(default='Gown', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='winner',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
