# Generated by Django 3.0.8 on 2020-07-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200727_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='bid_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='winner',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
