# Generated by Django 3.0.8 on 2020-07-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200728_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='bid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='winner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
