# Generated by Django 3.0.8 on 2020-07-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200730_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.CharField(max_length=255),
        ),
    ]
