# Generated by Django 3.0.8 on 2020-08-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_bid', models.IntegerField()),
                ('listing', models.ForeignKey(default='closed', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='listing', to='auctions.Listing')),
                ('winner', models.ForeignKey(default='ananemous', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
