# Generated by Django 3.0.8 on 2020-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='listing',
        ),
        migrations.AddField(
            model_name='winner',
            name='title',
            field=models.CharField(default='tem', max_length=64),
            preserve_default=False,
        ),
    ]
