# Generated by Django 3.0.8 on 2020-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200801_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='victor',
            field=models.CharField(max_length=64),
        ),
    ]
