# Generated by Django 3.0.8 on 2020-08-01 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200801_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='date_closed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
